name: Terraform Plan and Apply Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited]
    branches:
      - main
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == '/refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - run: |
          if jq . >/dev/null 2>&1 <<<'{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'; then
              echo "Parsed JSON successfully and got something other than false/null"
          else
              echo "Failed to parse JSON, or got false/null"
          fi      

      - name: Azure login
        uses: azure/login@v1 
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.10"
      
      - run: terraform init
      
      - run: terraform plan